### ISSUE TITLE
为什么initGetuiSdk会是一个get？

### ISSUE THREAD

**Issue by cy-mjy** [GetuiLaboratory/getui-flutter-plugin#12]
initGetuiSdk怎么会是作为一个get?它不是一个void嘛？根据使用文档写就直接报错了。

**Comment by eric112** [comment]
另外，有没有考虑提供一个方法，可以直接进行本地推送的？

**Comment by monkeydbobo** [comment]
本地推送指的是创建本地通知吗。如果想创建本地通知可以使用本地通知的插件啊
