### ISSUE TITLE
在 iOS 13 中推送消息不弹出

### ISSUE THREAD

**Issue by ZZsuper** [GetuiLaboratory/getui-flutter-plugin#16]
在 #15 问题解决（引入了 [flutter_call_kit](https://pub.dev/packages/flutter_call_kit) ）之后，iOS 13 的设备应用在后台时不弹出消息推送，iOS 12 设备正常；

初始化 GetuiSdk 的代码和[文档](https://github.com/GetuiLaboratory/getui-flutter-plugin/blob/master/README.md)中的一样;
 flutter doctor:
```txt
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.4 18E194d, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)
```
Xcode 中的设置也是一样的：
![image](https://user-images.githubusercontent.com/32979727/68357066-1edc0000-014f-11ea-932c-b3315946c534.png)

iOS 13 启动应用时控制台有这样的信息(1)：
```txt
[] nw_connection_copy_connected_path [C3] Client called nw_connection_copy_connected_path on unconnected nw_connection
[] tcp_connection_is_cellular No connected path
[] nehelper sent invalid result code [1] for Wi-Fi information request
```

将应用转为后台运行时，有这样的信息( [flutter issue #41095](https://github.com/flutter/flutter/issues/41095) )：
```txt
Can't end BackgroundTask: no background task exists with identifier 10 (0xa), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
```

上面这两条控制台信息在 iOS 12 设备上时不存在的，会是这个原因吗？我并不懂 iOS。。。

**Comment by Ezreal-lup** [comment]
![image](https://user-images.githubusercontent.com/40780223/68361045-48038d00-015d-11ea-857f-08a8475326c4.png)
你用我们github上面的这个demo试一下，AppID、AppKey、Appsecret替换成你自己的参数

**Comment by Ezreal-lup** [comment]
如果还是不行的话，你联系我们客服，把你的demo发过来看看

**Comment by ZZsuper** [comment]
> 如果还是不行的话，你联系我们客服，把你的demo发过来看看

现在可以了，刚开始我运行 demo 的时候也不行，应该是 deviceToken 的原因，我检测 deviceToken的时候提示链接错误，过了一会儿，重新安装几遍 再测 deviceToken 就成功了；
然后我再测我的 app 就收到消息了。。。
用的同一个 AppID、AppKey、Appsecret
