### ISSUE TITLE
bug：1、resume   2、resetBadge 

### ISSUE THREAD

**Issue by Jokergz** [GetuiLaboratory/getui-flutter-plugin#20]
Getuiflut().resumePush();  
应该是清空通知吗？
调用报错！
如果不是清空通知的话
哪个是，看文档上边是 clearAllNotificationForNotificationBar
插件上也没有调用这个呀。

源码GetuiflutPlugin.M
- handleMethodCall：result  
47 行是不是有问题？

Getuiflut().resetBadge()；
这个是复位角标吗？好像无效

**Comment by Mr-xiaomo** [comment]
Getuiflut().resetBadge()；
这个只是同步个推服务器，清除服务器上的角标数量。本地不会生效，目前。

**Comment by aklee** [comment]
建议升级至最新版本， `setLocalBadge`用于设定app本地badge，`setBadge`用于同步服务端badge。 若要clearAllNotificationForNotificationBar，可以通过设定setLocalBadge(0)
