### ISSUE TITLE
iOS 在 Kill 掉 App 的时候收到的 APNs 推送，点击后没有进入对应的回调

### ISSUE THREAD

**Issue by angelen10** [GetuiLaboratory/getui-flutter-plugin#22]
您好，我 Debug 了一下，在 iOS 上点击某条消息是进入 onReceiveNotificationResponse 回调的（App 在前台或者后台时），但是当 Kill 掉 App 之后，APNs 推送的确可以收到，但是点击这条推送并没有走 onReceiveNotificationResponse 回调（我是使用 Toast 来测试的），这是为何呢？

另外， 在前台的时候发送透传消息接收到的回调是 onReceivePayload，如果此时也要发送一条横幅通知，如果做到呢？是需要在对应的 iOS 和安卓分别提供原生的方法给 Flutter 调用吗？

再者，这些方法居然是干嘛的呢：onNotificationMessageClicked、onNotificationMessageArrived、onReceiveMessageData。发现代码没有在这些回调出现过，但是这命名感觉是点击了消息、消息到达、收到消息啥的，这不是跟上面的两个回调重叠？还是有做其他考虑？

**Comment by XutongGithub** [comment]
我也遇到了App进程关闭后，无法回调，我推测是flutter初始化个推回调延时了。目前在原生onReceiveNotificationResponse回调的时候做了延时解决。

**Comment by XutongGithub** [comment]
在前台的时候发送透传消息接收到的回调是 onReceivePayload，如果此时也要发送一条横幅通知，如果做到呢？是需要在对应的 iOS 和安卓分别提供原生的方法给 Flutter 调用吗？
这个问题，如果要给原生发送通知的话，需要原生实现，在后台的java端也有设置发送透传消息的机制。

**Comment by aklee** [comment]
@XutongGithub  苹果官网建议静默消息不设定横幅、badge、sound。 如果要提醒用户建议不用静默通知，也可以在收到透传后自行做本地通知动作

**Comment by aklee** [comment]
@angelen10 可以更新插件版本，新增了`getLaunchNotification`用于获取启动后的apns参数。
