### ISSUE TITLE
ios continueUserActivity 回调return true

### ISSUE THREAD

**Issue by joeyczz** [GetuiLaboratory/getui-flutter-plugin#26]
![image](https://user-images.githubusercontent.com/15942257/81469114-dc869f00-9215-11ea-9416-076e00809f7e.png)

会导致其他sdk无法接收 continueUserActivity 
![image](https://user-images.githubusercontent.com/15942257/81469162-19eb2c80-9216-11ea-954f-863bce2bf11e.png)

**Comment by leechan** [comment]
用了uni_links， iOS上一直收不到Universal Links 的监听，已经查到大概是个推引起的，感谢让我知道具体影响的地方，希望个推早点修复一下吧。

**Comment by aklee** [comment]
参考：
setPushMode(0)  关闭推送
setPushMode(1)   打开推送
