### ISSUE TITLE
ios 没有stopPush

### ISSUE THREAD

**Issue by yuexunshi** [GetuiLaboratory/getui-flutter-plugin#32]
ios系统，换手机登录账号后，旧手机还能接受推送，新登录的手机收不到推送。插件里没有实现ios的stopPush，是什么原因？

**Comment by aklee** [comment]
不同手机或App对应的cid都是不同的，可以根据业务需求给对应的cid推送消息即可。

**Comment by aklee** [comment]
参考：
setPushMode(0) 关闭推送
setPushMode(1) 打开推送
