### ISSUE TITLE
flutter 升级到1.7.8 getui插件收不到回调。

### ISSUE THREAD

**Issue by AndroidZern** [GetuiLaboratory/getui-flutter-plugin#4]
如题。

**Comment by monkeydbobo** [comment]
https://github.com/flutter/flutter/issues/34993 在高版本的flutter上会出现这种问题，在0.0.9版本的getui flutter插件修复了这个问题。或者
![image](https://user-images.githubusercontent.com/13078217/61194936-8b8e4300-a6f7-11e9-8983-0b8c82ef89e8.png)
回退到上图的版本也可以正常使用

**Comment by AndroidZern** [comment]
![image](https://user-images.githubusercontent.com/15031729/61267567-0b391200-a7cb-11e9-8127-7288cb649c69.png)
您好。请问插件是否已经更新到pub.dev上面了。 我这边引用不到。麻烦发布到pub.dev

**Comment by AndroidZern** [comment]
更新到^0.0.9问题fixed.
