### ISSUE TITLE
官方插件初始化报错

### ISSUE THREAD

**Issue by XutongGithub** [GetuiLaboratory/getui-flutter-plugin#45]
### iOS端：初始化报错

`[GeTuiSdk startSdkWithAppId:ConfigurationInfo[@"appId"] appKey:ConfigurationInfo[@"appKey"] appSecret:ConfigurationInfo[@"appSecret"] delegate:self];`

**Comment by aklee** [comment]
API文档请参考文档中心：https://docs.getui.com/getui/mobile/ios/api/
