### ISSUE TITLE
Xcode15环境运行报错

### ISSUE THREAD

**Issue by Steven-Yung** [GetuiLaboratory/getui-flutter-plugin#57]
ARC Semantic Issue (Xcode): No known class method for selector 'registerActivityToken:'
/Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/getuiflut-0.2.21/ios/Classes/GetuiflutPlugin.m
:222:14

Xcode查看是个推SDK3.0.3没有registerActivityToken这个方法？

**Comment by Kevin-osss** [comment]
在 Podfile中修改 GTSDK 为 3.0.2.0
![image](https://github.com/GetuiLaboratory/getui-flutter-plugin/assets/98069105/984dc841-059b-4f7d-9b0b-7fb2f03042e6)
然后在 xcode 中修改 ios 最低系统为 ios12
