### ISSUE TITLE
swift 项目有问题

### ISSUE THREAD

**Issue by 3067200952** [GetuiLaboratory/getui-flutter-plugin#7]

**Comment by 3067200952** [comment]
用不了

**Comment by 3067200952** [comment]
没人的吗？？？？？？？？

**Comment by Ezreal-lup** [comment]
你好，请问下你的问题具体是什么，可以详细说明一下么。flutter开发APP，使用个推插件，只需要在pubspec.yaml文件里面添加个推插件，然后在自己主页面去初始化个推SDK，然后去监听透传消息和APNS消息。

**Comment by 3067200952** [comment]
创建项目的时候使用swift，跑不起来，使用了静态库，在将s.static_framework = true到podspec文件后，调用时出现了MissingPluginException的异常

**Comment by Ezreal-lup** [comment]
解决方案

方案一：flutter clean一下，再次 flutter run/build

方案二：将flutter run的进程终止掉重新 flutter run/build

方案三：看看你的FlutterPluginRegistrant产物是否存在，是否更新了

如果还是没有解决的话，你看能否把你的demo发过来，我们这边看看！

**Comment by 3067200952** [comment]
ok，解决了，我同时调用了安卓和iOS的初始化，麻烦添加一下说明，两个平台需要分开使用，以及添加s.static_framework = true的问题

**Comment by Ezreal-lup** [comment]
嗯，好的，我们后面会在文档上面说明的！感谢你对个推的支持！！！
