### ISSUE TITLE
iOS消息回调能把是否为离线消息也传过来吗

### ISSUE THREAD

**Issue by xqqlv** [GetuiLaboratory/getui-flutter-plugin#8]

**Comment by monkeydbobo** [comment]
iOS应该没有离线或者在线消息的区别，都是通过apns下发到手机上的，所以一直都可以收到

**Comment by xqqlv** [comment]
![image](https://user-images.githubusercontent.com/16477726/65014325-e68b2300-d950-11e9-9931-1b0d28c051ca.png)

**Comment by xqqlv** [comment]
我的意思是能不能把offLine这个字段也传过来

**Comment by monkeydbobo** [comment]
@Ezreal-lup

**Comment by Ezreal-lup** [comment]
Getuiflut().addEventHandler(
    onReceivePayload:(String message) async {
          // 应用在前台，收到的透传消息 
   }，
   
   onReceiveNotificationResponse:(String message) async {
          // 应用在后台或应用杀死情况下，收到的APNS消息 
   }，
)

**Comment by xqqlv** [comment]
我现在能收到消息，也知道是哪个回调，我的意思是消息中没有offLine这个字段，能不能传过来

**Comment by Ezreal-lup** [comment]
嗯，好的

**Comment by Ezreal-lup** [comment]
已经修改，你可以看一下 @xqqlv

**Comment by xqqlv** [comment]
![image](https://user-images.githubusercontent.com/16477726/65038780-54504280-d983-11e9-9bff-50ab051e7314.png)
应该用EventHandlerMap这个类型吧 @Ezreal-lup

**Comment by Ezreal-lup** [comment]
用的就是EventHandlerMap这个类型，你用最新的版本看看
