### ISSUE TITLE
clientId 没有回调

### ISSUE THREAD

**Issue by 123lxw123** [GetuiLaboratory/getui-flutter-plugin#9]

**Comment by 123lxw123** [comment]
集成后 Android Studio 点击 Run 完成后，再点击 Run 没有接收到 clientId 的回调，重新 Run 应该看作是重启 App，此时应该有回调。

**Comment by monkeydbobo** [comment]
Android初始化的操作和init按钮绑定在一起的，你重启是不会初始化个推sdK,必须点击了按钮才会初始化，你可以看看demo里面是如何写的

**Comment by monkeydbobo** [comment]
https://github.com/GetuiLaboratory/getui-flutter-plugin/blob/master/example/lib/main.dart

**Comment by 123lxw123** [comment]
不是运行 demo，是集成到我们项目里了，在 main.dart 的  main() 中 Android 调用了 Getuiflut.initGetuiSdk，iOS 调用了 Getuiflut().startSdk()，然后
 ```Getuiflut().addEventHandler(
      onReceiveClientId: (clientId) async {
        LogUtil.print('个推 clientId 回调 ==> $clientId');
        if (!StringUtil.isNullOrBlank(clientId)) {
          Service.rest.options.headers['device_id'] = clientId;
          StoreContainer.dispatch(InitDeviceIdAction(deviceId: clientId));
        }
      })
```
首次运行 Run 都是正常回调 clientId 的，再次 Run 的时候会重新走 main()，但是确没有回调 clientId，iOS 返回桌面再回来才会回调，Android 只有 stop Debug，再次 Run 才会回调

**Comment by 123lxw123** [comment]
或者添加 iOS 获取 clientId 的方法，现在 getClientId 只是 Android 实现了

**Comment by 123lxw123** [comment]
请问可以添加下 iOS 获取 clientId 的方法吗

**Comment by monkeydbobo** [comment]
@Ezreal-lup

**Comment by Ezreal-lup** [comment]
已经更新了 @123lxw123
